### ISSUE TITLE
Pub/sub subscriptions aren't reused or cancelled.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/annotation-service#50]

**Comment by jlm123hi** [comment]
Just a note, since I saw this in my inbox, the subscriptions should definitely not be reused, because each instance needs to be able to get every message.

It is definitely better to delete the subscriptions, but if they don't get deleted, subscriptions that are unused will be automatically deleted by GCP after 30 days.

**Comment by pboothe** [comment]
Obsolete.
